config/routes.rb
Rails.application.routes.draw do
  resources :movie_locations
  resources :movie_actors
  resources :neighbourhoods
  resources :cities
  resources :screen_locations
  resources :production_companies
  resources :actors
  resources :movies

  root :to => 'movies#index'
  post '/' => 'movies#index'
  post '/trial' => 'movies#trial'
  get 'search_movie' => 'movies#search_movie', :as => :search_movie
  get 'search_actor' => 'movies#search_actor', :as => :search_actor
  get 'search_director' => 'movies#search_director', :as => :search_director
  get 'search_release_year' => 'movies#search_release_year', :as => :search_release_year

end

app/models/neighbourhood.rb
class Neighbourhood < ActiveRecord::Base
  belongs_to :city
  has_many :screen_locations
end

app/controllers/neighbourhoods_controller.rb
class NeighbourhoodsController < ApplicationController
  before_action :set_neighbourhood, only: [:show, :edit, :update, :destroy]

  # GET /neighbourhoods
  # GET /neighbourhoods.json
  def index
    @neighbourhoods = Neighbourhood.all
  end

  # GET /neighbourhoods/1
  # GET /neighbourhoods/1.json
  def show
  end

  # GET /neighbourhoods/new
  def new
    @neighbourhood = Neighbourhood.new
  end

  # GET /neighbourhoods/1/edit
  def edit
  end

  # POST /neighbourhoods
  # POST /neighbourhoods.json
  def create
    @neighbourhood = Neighbourhood.new(neighbourhood_params)

    respond_to do |format|
      if @neighbourhood.save
        format.html { redirect_to @neighbourhood, notice: 'Neighbourhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighbourhood }
      else
        format.html { render :new }
        format.json { render json: @neighbourhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighbourhoods/1
  # PATCH/PUT /neighbourhoods/1.json
  def update
    respond_to do |format|
      if @neighbourhood.update(neighbourhood_params)
        format.html { redirect_to @neighbourhood, notice: 'Neighbourhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighbourhood }
      else
        format.html { render :edit }
        format.json { render json: @neighbourhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighbourhoods/1
  # DELETE /neighbourhoods/1.json
  def destroy
    @neighbourhood.destroy
    respond_to do |format|
      format.html { redirect_to neighbourhoods_url, notice: 'Neighbourhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighbourhood
      @neighbourhood = Neighbourhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighbourhood_params
      params.require(:neighbourhood).permit(:title)
    end
end

app/helpers/neighbourhoods_helper.rb
module NeighbourhoodsHelper
end

app/views/neighbourhoods/_form.html.erb
<%= form_for(@neighbourhood) do |f| %>
  <% if @neighbourhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighbourhood.errors.count, "error") %> prohibited this neighbourhood from being saved:</h2>

      <ul>
      <% @neighbourhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neighbourhoods/edit.html.erb
<h1>Editing Neighbourhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighbourhood %> |
<%= link_to 'Back', neighbourhoods_path %>

app/views/neighbourhoods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Neighbourhoods</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighbourhoods.each do |neighbourhood| %>
      <tr>
        <td><%= neighbourhood.title %></td>
        <td><%= link_to 'Show', neighbourhood %></td>
        <td><%= link_to 'Edit', edit_neighbourhood_path(neighbourhood) %></td>
        <td><%= link_to 'Destroy', neighbourhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighbourhood', new_neighbourhood_path %>

app/views/neighbourhoods/new.html.erb
<h1>New Neighbourhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighbourhoods_path %>

app/views/neighbourhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @neighbourhood.title %>
</p>

<%= link_to 'Edit', edit_neighbourhood_path(@neighbourhood) %> |
<%= link_to 'Back', neighbourhoods_path %>