config/routes.rb
Rails.application.routes.draw do
  resources :movie_locations
  resources :movie_actors
  resources :neighbourhoods
  resources :cities
  resources :screen_locations
  resources :production_companies
  resources :actors
  resources :movies

  root :to => 'movies#index'
  post '/' => 'movies#index'
  post '/trial' => 'movies#trial'
  get 'search_movie' => 'movies#search_movie', :as => :search_movie
  get 'search_actor' => 'movies#search_actor', :as => :search_actor
  get 'search_director' => 'movies#search_director', :as => :search_director
  get 'search_release_year' => 'movies#search_release_year', :as => :search_release_year

end

app/models/screen_location.rb
class ScreenLocation < ActiveRecord::Base
  has_many :movie_locations
  has_many :movies, through: :movie_locations
  belongs_to :neighbourhood
end

app/controllers/screen_locations_controller.rb
class ScreenLocationsController < ApplicationController
  before_action :set_screen_location, only: [:show, :edit, :update, :destroy]

  # GET /screen_locations
  # GET /screen_locations.json
  def index
    @screen_locations = ScreenLocation.all
  end

  # GET /screen_locations/1
  # GET /screen_locations/1.json
  def show
  end

  # GET /screen_locations/new
  def new
    @screen_location = ScreenLocation.new
  end

  # GET /screen_locations/1/edit
  def edit
  end

  # POST /screen_locations
  # POST /screen_locations.json
  def create
    @screen_location = ScreenLocation.new(screen_location_params)

    respond_to do |format|
      if @screen_location.save
        format.html { redirect_to @screen_location, notice: 'Screen location was successfully created.' }
        format.json { render :show, status: :created, location: @screen_location }
      else
        format.html { render :new }
        format.json { render json: @screen_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screen_locations/1
  # PATCH/PUT /screen_locations/1.json
  def update
    respond_to do |format|
      if @screen_location.update(screen_location_params)
        format.html { redirect_to @screen_location, notice: 'Screen location was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen_location }
      else
        format.html { render :edit }
        format.json { render json: @screen_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screen_locations/1
  # DELETE /screen_locations/1.json
  def destroy
    @screen_location.destroy
    respond_to do |format|
      format.html { redirect_to screen_locations_url, notice: 'Screen location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen_location
      @screen_location = ScreenLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screen_location_params
      params.require(:screen_location).permit(:name, :address, :latitude, :longitude, :city_id, :neighbourhood)
    end
end

app/helpers/screen_locations_helper.rb
module ScreenLocationsHelper
end

app/views/screen_locations/_form.html.erb
<%= form_for(@screen_location) do |f| %>
  <% if @screen_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screen_location.errors.count, "error") %> prohibited this screen_location from being saved:</h2>

      <ul>
      <% @screen_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :neighbourhood %><br>
    <%= f.number_field :neighbourhood %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screen_locations/edit.html.erb
<h1>Editing Screen Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @screen_location %> |
<%= link_to 'Back', screen_locations_path %>

app/views/screen_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Screen Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th>Neighbourhood</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screen_locations.each do |screen_location| %>
      <tr>
        <td><%= screen_location.name %></td>
        <td><%= screen_location.address %></td>
        <td><%= screen_location.latitude %></td>
        <td><%= screen_location.longitude %></td>
        <td><%= screen_location.city_id %></td>
        <td><%= screen_location.neighbourhood %></td>
        <td><%= link_to 'Show', screen_location %></td>
        <td><%= link_to 'Edit', edit_screen_location_path(screen_location) %></td>
        <td><%= link_to 'Destroy', screen_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screen location', new_screen_location_path %>

app/views/screen_locations/new.html.erb
<h1>New Screen Location</h1>

<%= render 'form' %>

<%= link_to 'Back', screen_locations_path %>

app/views/screen_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @screen_location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @screen_location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @screen_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @screen_location.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @screen_location.city_id %>
</p>

<p>
  <strong>Neighbourhood:</strong>
  <%= @screen_location.neighbourhood %>
</p>

<%= link_to 'Edit', edit_screen_location_path(@screen_location) %> |
<%= link_to 'Back', screen_locations_path %>