config/routes.rb
Rails.application.routes.draw do
  resources :movie_locations
  resources :movie_actors
  resources :neighbourhoods
  resources :cities
  resources :screen_locations
  resources :production_companies
  resources :actors
  resources :movies

  root :to => 'movies#index'
  post '/' => 'movies#index'
  post '/trial' => 'movies#trial'
  get 'search_movie' => 'movies#search_movie', :as => :search_movie
  get 'search_actor' => 'movies#search_actor', :as => :search_actor
  get 'search_director' => 'movies#search_director', :as => :search_director
  get 'search_release_year' => 'movies#search_release_year', :as => :search_release_year

end

app/models/movie_location.rb
class MovieLocation < ActiveRecord::Base
  belongs_to :movie
  belongs_to :screen_location
end

app/controllers/movie_locations_controller.rb
class MovieLocationsController < ApplicationController
  before_action :set_movie_location, only: [:show, :edit, :update, :destroy]

  # GET /movie_locations
  # GET /movie_locations.json
  def index
    @movie_locations = MovieLocation.all
  end

  # GET /movie_locations/1
  # GET /movie_locations/1.json
  def show
  end

  # GET /movie_locations/new
  def new
    @movie_location = MovieLocation.new
  end

  # GET /movie_locations/1/edit
  def edit
  end

  # POST /movie_locations
  # POST /movie_locations.json
  def create
    @movie_location = MovieLocation.new(movie_location_params)

    respond_to do |format|
      if @movie_location.save
        format.html { redirect_to @movie_location, notice: 'Movie location was successfully created.' }
        format.json { render :show, status: :created, location: @movie_location }
      else
        format.html { render :new }
        format.json { render json: @movie_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_locations/1
  # PATCH/PUT /movie_locations/1.json
  def update
    respond_to do |format|
      if @movie_location.update(movie_location_params)
        format.html { redirect_to @movie_location, notice: 'Movie location was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_location }
      else
        format.html { render :edit }
        format.json { render json: @movie_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_locations/1
  # DELETE /movie_locations/1.json
  def destroy
    @movie_location.destroy
    respond_to do |format|
      format.html { redirect_to movie_locations_url, notice: 'Movie location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_location
      @movie_location = MovieLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_location_params
      params.require(:movie_location).permit(:movie_id, :location_id)
    end
end

app/helpers/movie_locations_helper.rb
module MovieLocationsHelper
end

app/views/movie_locations/_form.html.erb
<%= form_for(@movie_location) do |f| %>
  <% if @movie_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_location.errors.count, "error") %> prohibited this movie_location from being saved:</h2>

      <ul>
      <% @movie_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_locations/edit.html.erb
<h1>Editing Movie Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_location %> |
<%= link_to 'Back', movie_locations_path %>

app/views/movie_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movie Locations</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_locations.each do |movie_location| %>
      <tr>
        <td><%= movie_location.movie_id %></td>
        <td><%= movie_location.location_id %></td>
        <td><%= link_to 'Show', movie_location %></td>
        <td><%= link_to 'Edit', edit_movie_location_path(movie_location) %></td>
        <td><%= link_to 'Destroy', movie_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie location', new_movie_location_path %>

app/views/movie_locations/new.html.erb
<h1>New Movie Location</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_locations_path %>

app/views/movie_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_location.movie_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @movie_location.location_id %>
</p>

<%= link_to 'Edit', edit_movie_location_path(@movie_location) %> |
<%= link_to 'Back', movie_locations_path %>